name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
  job2:
    needs: job1
    name: Test2
    runs-on: ubuntu-latest
      name: deploying code in shopify
      steps:
        - uses: discolabs/deploy-shopify-theme-action@v1
          with:
            store: experimental-theme.myshopify.com
            password: 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
            theme_id: 121935560773
            path: dist
            additional_args: ''