name: Deploy to Staging
on: [push]
jobs:
  Install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: yarn install
    - run: yarn build
    - run: ls -l
  Deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: Install
    steps:   
      - run: ls -l   
      - uses: discolabs/deploy-shopify-theme-action@v1
        with:
          store: experimental-theme.myshopify.com
          password: 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
          theme_id: 121935560773
          path: dist
          additional_args: '--ignored-file=config/settings_data.json'