name: Deploy to Staging
on: [push]
jobs:
  build_and_install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: yarn install
    - run: yarn build
    - name: Archive compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: distribution_folder
        path: dist
  Deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build_and_install
    steps:
      - run: mkdir dist
      - name: Download the dist folder
        uses: actions/download-artifact@v3
        with:
          name: distribution_folder 
          path: ~/dist
      - run: ls -l
      - uses: discolabs/deploy-shopify-theme-action@v1
        with:
          store: experimental-theme.myshopify.com
          password: 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
          theme_id: 121935560773
          path: dist
          additional_args: '--ignored-file=config/settings_data.json'

