name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: actions/upload-artifact@v2
        with:
          name: Github_Actions_Experimental_Theme
          path: dist
      - uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: 1c0f9773f9c68ec5ec3208f4558cf775
          SHOPIFY_STORE_URL: experimental-theme.myshopify.com
          SHOPIFY_THEME_ID: 121935560773
          THEME_PATH: ./