name: Validate Pull Requests
on: [push]
jobs:
  build_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: Archive compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution_folder
          path: dist

  deploy_to_staging_theme:
    runs-on: ubuntu-latest
    needs: build_and_install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: main